### ISSUE TITLE
Ignore files?

### ISSUE THREAD

**Issue by lf94** [lyphtec/markdown-serve#8]
My js and css files are getting caught by this. Need a way to ignore them.

**Comment by lyphtec** [comment]
Hi,

This shouldn't be the case.  markdown-serve only resolves files with an ".md" extension by default (which can be overridden by an option).  Normally you would have the [Express static](https://expressjs.com/en/starter/static-files.html) handler specified first and this should pickup all your static assets before any other routes.

See [more examples](https://github.com/lyphtec/markdown-serve-examples) of markdown-serve where the static css file is never handled by it
